<?php require 'Templates/Layout/header.phtml'; ?>

<div class="container mt-4 informacion">
    <h1 class="mb-4"><?= htmlspecialchars($film->Nombre_pelicula) ?></h1>
    <div class="card">
        <div class="card-body">
            <p class="card-text"><strong>Director:</strong> <?= htmlspecialchars($film->director) ?></p>
            <p class="card-text"><strong>Género:</strong> <?= htmlspecialchars($film->genero) ?></p>
            <p class="card-text"><strong>Idioma:</strong> <?= htmlspecialchars($film->Idioma) ?></p>
            <p class="card-text"><strong>Lanzamiento:</strong> <?= date("d/m/Y", strtotime($film->Lanzamiento)) ?></p>
            <p class="card-text"><strong>Productora:</strong> <?= htmlspecialchars($film->Nombre_productora) ?></p>
        </div>
    </div>
</div>

<div class="container mt-5">
    <ul class="row list-unstyled">
        <?php foreach($films as $film): ?>
            <li class="col-md-4 mb-4">
                <div class="card">
                    <div class="film-image" style="width: 100%; height: 200px; background-color: #f0f0f0; border: 5px solid black;">
                    <img src="<?= htmlspecialchars($film->imagen_pelicula) ?>" alt="<?= htmlspecialchars($film->Nombre_pelicula) ?>" class="card-img-top" style="height: 100%; object-fit: cover;">
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">
                            <a href="<?= BASE_URL ?>pelicula/<?= $film->id_peliculas ?>" class="text-decoration-none text-danger"><?= htmlspecialchars($film->Nombre_pelicula) ?></a>
                        </h3>
                        <p class="card-text">Género: <?= htmlspecialchars($film->genero) ?></p>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>

    <p class="mt-3"><small>Mostrando <?= count($films) ?> Películas</small></p>
</div>

<?php require 'Templates/Layout/footer.phtml'; ?>
