
<div class="container mt-5 form">
    <h1 class="text-center">Agregar Nueva Película</h1>
    
    <!-- Formulario para agregar una nueva película -->
    <form action="nueva" method="POST" enctype="multipart/form-data">
        <div class="form-group">
            <label for="nameFilm">Nombre de la Película *</label>
            <input type="text" class="form-control" id="nameFilm" name="name_film" required>
        </div>
        
        <div class="form-group">
            <label for="releaseDate">Lanzamiento *</label>
            <input type="date" class="form-control" id="releaseDate" name="date" required>
        </div>
        
        <div class="form-group">
            <label for="director">Director *</label>
            <input type="text" class="form-control" id="director" name="director" required>
        </div>
        
        <div class="form-group">
            <label for="genre">Género *</label>
            <input type="text" class="form-control" id="genre" name="genre" required>
        </div>
        
        <div class="form-group">
            <label for="language">Idioma *</label>
            <select required name="language" class="form-control" id="language">
                <option value="Ingles">Inglés</option>
                <option value="Español">Español</option>
                <option value="Frances">Francés</option>
                <option value="Portugues">Portugués</option>
            </select>
        </div>
        
        <div class="form-group">
            <label for="producerSelect">Productora *</label>
            <select required name="id_productoras" class="form-control" id="producerSelect">
                <option value="">Seleccione una productora</option>
                <?php if (!empty($producers)): ?>
                    <?php foreach ($producers as $producer): ?>
                        <option value="<?= htmlspecialchars($producer->id_productora); ?>"><?= htmlspecialchars($producer->nombre_productora); ?></option>
                    <?php endforeach; ?>
                <?php else: ?>
                    <option value="">No hay productoras disponibles</option>
                <?php endif; ?>
            </select>
            <a href="agregarProductora" class="text-decoration-none">Agregar productora</a>
        </div>
        <div class="form-group ">
            <label for="image_film"> url imagen</label>
            <input type="file" class="form-control" id="image_film" name="image_film"
                   value="<?= isset($producer) ? htmlspecialchars($producer->imagen_pelicula) : '' ?>">
        </div>

        <button type="submit" class="btn btn-primary btn-block">Guardar</button>
    </form>
</div>

