<?php require 'Templates/Layout/header.phtml' ?>

<?php require 'Templates/Films/form_film.phtml' ?>

<div class="container mt-5">
    <ul class="row list-unstyled">
        <?php foreach($films as $film): ?>
            <li class="col-md-4 mb-4">
                <div class="card">
                    <div class="film-image" style="width: 100%; height: 200px; background-color: #f0f0f0; border: 5px solid black;">
                    <img src="<?= htmlspecialchars($film->imagen_pelicula) ?>" alt="<?= htmlspecialchars($film->Nombre_pelicula) ?>" class="card-img-top" style="height: 100%; object-fit: cover;">
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">
                            <a href="pelicula/<?= $film->id_peliculas ?>" class="text-decoration-none text-danger"><?= htmlspecialchars($film->Nombre_pelicula) ?></a>
                        </h3>
                        <p class="card-text">Género: <?= htmlspecialchars($film->genero) ?></p>
                        <div class="d-flex justify-content-between">
                            <a href="eliminar/<?= $film->id_peliculas ?>" class='btn btn-danger btn-sm'>Borrar</a>
                            <a href="editar/<?= $film->id_peliculas ?>" class='btn btn-warning btn-sm'>Actualizar</a>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>

    <p class="mt-3"><small>Mostrando <?= count($films) ?> Películas</small></p>
</div>

<?php require 'Templates/Layout/footer.phtml' ?>
