<?php require 'Templates/Layout/header.phtml' ?>
<div class="container mt-5 form">
    <form method="POST" action="<?= BASE_URL ?>editarProductora/<?= $producer->id_productora ?>" enctype="multipart/form-data">
        <div class="form-group">
            <label for="input_name_producer">Nombre del productor</label>
            <input type="text" class="form-control" id="input_name_producer" name="input_name_producer"
                   value="<?= isset($producer) ? htmlspecialchars($producer->nombre_productora) : '' ?>" required>
        </div>

        <div class="form-group mt-3">
            <label for="input_year_foundation">Año de fundación</label>
            <input type="text" class="form-control" id="input_year_foundation" name="input_year_foundation"
                   value="<?= isset($producer) ? htmlspecialchars($producer->año_fundacion) : '' ?>" required>
        </div>

        <div class="form-group mt-3">
            <label for="founders">Fundador/es</label>
            <input type="text" class="form-control" id="founders" name="founders"
                   value="<?= isset($producer) ? htmlspecialchars($producer->fundador_es) : '' ?>" required>
        </div>

        <div class="form-group mt-3">
            <label for="country_origin">País de origen</label>
            <input type="text" class="form-control" id="country_origin" name="country_origin"
                   value="<?= isset($producer) ? htmlspecialchars($producer->pais_origen) : '' ?>" required>
        </div>

        <div class="form-group mt-3">
            <label for="image_producer">Imagen del productor</label>
            <input type="file" class="form-control" id="image_producer" name="image_producer" required>
        </div>

        <div class="form-group mt-4">
            <button type="submit" class="btn btn-primary">Modificar</button>
        </div>
    </form>
</div>
