<?php require 'Templates/Layout/header.phtml' ?>

<div class="container mt-5">
    <div class="row">
        <?php foreach($producers as $producer): ?>
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="film-image" style="height: 200px; background-color: #f0f0f0; border: 5px solid black;">
                    <img src="<?= htmlspecialchars($producer->imagen_productora) ?>" alt="<?= htmlspecialchars($producer->nombre_productora) ?>" class="card-img-top" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="verProductora/<?= htmlspecialchars($producer->id_productora) ?>" class="text-decoration-none text-danger"><?= htmlspecialchars($producer->nombre_productora) ?></a>
                        </h5>
                        <p class="card-text"><?= htmlspecialchars($producer->pais_origen) ?></p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>    
</div>

<?php require 'Templates/Layout/footer.phtml' ?>
