
<?php require 'Templates/Layout/header.phtml' ?>
<div class="container mt-">
    <ul class="row list-unstyled">
    <h1 class="text-center">Peliculas de la productora</h1>
        <?php foreach($films as $film): ?>
            <li class="col-md-4 mb-4">
                <div class="card">
                    <div class="film-image" style="width: 100%; height: 200px; background-color: #f0f0f0; border: 5px solid black;">
                    <img src="<?= htmlspecialchars($film->imagen_pelicula) ?>" alt="<?= htmlspecialchars($film->Nombre_pelicula) ?>" class="card-img-top" style="height: 100%; object-fit: cover;">
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">
                            <a href="<?= BASE_URL ?>pelicula/<?= $film->id_peliculas ?>" class="text-decoration-none text-danger"><?= htmlspecialchars($film->Nombre_pelicula) ?></a>
                        </h3>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<?php require 'Templates/Layout/footer.phtml' ?>