
<div class="container">
    <form action="productoraAgregada" method="post">
        <div class="form-group">
            <label for="name_producer">Nombre productora</label>
            <input class="form-control" id="name_producer" name="input_name_producer" >
        </div>
        <div class="form-group">
            <label for="year_foundation">Año de fundacion</label>
            <input class="form-control" id="year_foundation" name="input_year_foundation">
        </div>
        <div class="form-group">
            <label for="founders">Fundador/es</label>
            <input class="form-control" id="founders"  name="founders">
    </div>
    <div class="form-group">
            <label for="country_origin">Pais de origen</label>
            <input class="form-control" id="country_origin"  name="country_origin">
    </div>
    
        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
</div>
