<?php require 'Templates/Layout/header.phtml' ?>
<div class="container mt-5">
    <h1 class="text-center">Agregar Nueva Película</h1>
    <form action="productoraAgregada" method="POST">
            <div class="form-group">
                <label for="name_producer">Nombre productora</label>
                <input type="text" class="form-control" id="name_producer" name="input_name_producer" required>
            </div>
            
            <div class="form-group">
                <label for="year_foundation">Año de fundacion</label>
                <input type="date" class="form-control" id="year_foundation" name="input_year_foundation" required>
            </div>
            
            <div class="form-group">
                <label for="founders">fundador/s</label>
                <input type="text" class="form-control" id="founders" name="founders" required>
            </div>
            
            <div class="form-group">
                <label for="country_origin">Pais de origen</label>
                <input type="text" class="form-control" id="country_origin" name="country_origin" required>
            </div>
            <button type="submit" class="btn btn-primary btn-block"><a href="<?=BASE_URL ?>agregar" class="nav-link px-2">agregar</a></button>
        </form>
</div>
<?php require 'Templates/Layout/footer.phtml' ?>