<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Películas</title>
</head>
<body>

    <!-- Formulario para agregar una nueva película -->
    <form action="nueva" method="POST">
        <div class="mb-3">
            <label for="nameFilm" class="form-label">Nombre de la Película *</label>
            <input type="text" class="form-control" id="nameFilm" name="name_film" required>
        </div>
        <div class="mb-3">
            <label for="releaseDate" class="form-label">Lanzamiento *</label>
            <input type="date" class="form-control" id="releaseDate" name="date" required>
        </div>
        <div class="mb-3">
            <label for="director" class="form-label">Director *</label>
            <input type="text" class="form-control" id="director" name="director" required>
        </div>
        <div class="mb-3">
            <label for="genre" class="form-label">Género *</label>
            <input type="text" class="form-control" id="genre" name="genre" required>
        </div>
        <div class="mb-3">
            <label for="language" class="form-label">Idioma *</label>
            <select required name="language" class="form-control" id="language">
                <option value="Ingles">Inglés</option>
                <option value="Español">Español</option>
                <option value="Frances">Francés</option>
                <option value="Portugues">Portugués</option>
            </select>
        </div>
        
        <div class="mb-3">
            <label for="producerSelect" class="form-label">Productora *</label>
            <select required name="id_productoras" class="form-control" id="producerSelect">
                <option value="">Seleccione una productora</option>
                <?php if (!empty($producers)): ?>
                    <?php foreach ($producers as $producer): ?>
                        <option value="<?= htmlspecialchars($producer->id_productoras); ?>"><?= htmlspecialchars($producer->nombre_productora); ?></option>
                    <?php endforeach; ?>
                <?php else: ?>
                    <option value="">No hay productoras disponibles</option>
                <?php endif; ?>
            </select>
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>

</body>
</html>
