
<div class="container">
    <form action="addPoducer" method="post">
        <div class="form-group">
            <label for="name_producer">name producer</label>
            <input class="form-control" id="name_producer" name="input_name_producer" >
        </div>
        <div class="form-group">
            <label for="year_foundation">Year offoundation</label>
            <input class="form-control" id="year_foundation" name="input_year_foundation">
        </div>
        <div class="form-group">
            <label for="Cuota_capital">Cuota_capital</label>
            <input class="form-control" id="Cuota_capital"  name="input_Cuota_capital">
    </div>
    <div class="form-group">
            <label for="Fecha_pago">Fecha_pago</label>
            <input class="form-control" id="Fecha_pago"  name="input_Fecha_pago">
    </div>
    
        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
</div>
