<?php require 'templates/layout/header.phtml'; ?>
<div class="container mt-5">
    <h2 class="text-center mb-4">Iniciar Sesión</h2>
    
    <?php if ($error): ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
    <?php endif; ?>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h5>Accede a tu cuenta</h5>
                </div>
                <div class="card-body">
                    <form method="post" action="login">
                        <div class="form-group mb-3">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" required>
                        </div>
                        <div class="form-group mb-4">
                            <label for="password">Contraseña</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Iniciar Sesión</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php require 'templates/layout/footer.phtml'; ?>
