<?php require 'Templates/Layout/header.phtml' ?>

<?php require 'Templates/form_film.phtml' ?>

<ul class="container">
    <div class="row">
        <?php foreach($films as $film): ?>
            <li class="col">
                <div class="film-card">
                    <!-- Div para la imagen de la película -->
                    <div class="film-image" style="width: 150px; height: 150px; background-color: #f0f0f0; border: 1px solid #ddd;">
                        <img src="" alt="<?= htmlspecialchars($film->Nombre_pelicula) ?>" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
                    <!--
                        date("d/m/y", strtotime($film->Lanzamiento))
                        htmlspecialchars($film->director)
                        htmlspecialchars($film->Idioma)

                        (Esto mejor lo muestro cuando navegue por cada pelicula)

                    -->

                    <!-- Nombre de la película y el género -->
                    <div class="film-info">
                        <h3><?= htmlspecialchars($film->Nombre_pelicula) ?></h3>
                        <p><?= htmlspecialchars($film->genero) ?></p>
                    </div>
                    <a href="eliminar/<?= $film->id_peliculas ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
                </div>
            </li>
        <?php endforeach ?>
    </div>    
</ul>

<p class="mt-3"><small>Mostrando <?= count($films) ?> Peliculas</small></p>

<?php require 'Templates/Layout/footer.phtml' ?>

           
   