<?php require 'Templates/Layout/header.phtml' ?>

<ul class="list-group">
    <?php foreach($films as $film): ?>
        <li class="list-group-item item-task">
            <div class="label">
                <!-- muestro el titulo de la pelicula -->
                <b><?= htmlspecialchars($film->Nombre_pelicula) ?></b> |
                <b><?= date("d/m/y", strtotime($film->Lanzamiento)) ?></b> |
                <b><?= htmlspecialchars($film->genero) ?></b> |
                <b><?= htmlspecialchars($film->director) ?></b> |
                <b><?= htmlspecialchars($film->Idioma) ?></b> |
            </div>
        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?= count($films) ?> Peliculas</small></p>

<?php require 'Templates/Layout/footer.phtml' ?>
