<?php require 'Templates/Layout/header.phtml' ?>

<?php require 'Templates/form_film.phtml' ?>

<ul class="container">
    <div class="row">
        <?php foreach($films as $film): ?>
            <li class="col">
                <div class="film-card">
                    <div class="film-image" style="width: 150px; height: 150px; background-color: #f0f0f0; border: 1px solid #ddd;">
                        <img src="" alt="<?= htmlspecialchars($film->Nombre_pelicula) ?>" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
                    <div class="film-info">
                        <!-- Cambié a un enlace aquí -->
                        <h3><a href="film/<?= $film->id_peliculas ?>" class="text-decoration-none"><?= htmlspecialchars($film->Nombre_pelicula) ?></a></h3>
                        <p>Genero: <?= htmlspecialchars($film->genero) ?></p>
                    </div>
                    <a href="eliminar/<?= $film->id_peliculas ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
                    <a href="editar/<?= $film->id_peliculas ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Actualizar</a>
                </div>
            </li>
        <?php endforeach ?>
    </div>    
</ul>


<p class="mt-3"><small>Mostrando <?= count($films) ?> Peliculas</small></p>

<?php require 'Templates/Layout/footer.phtml' ?>

           
   