<?php require 'Templates/Layout/header.phtml' ?>

<div class="container">
    <div class="row">
        <?php foreach($producers as $producer): ?>
            <div class="col-md-4">
                <div class="card producer-card mb-3">
                    <div class="card-body">
                        <!-- Nombre de la película y el país de origen -->
                        <h3 class="card-title">
                            <a href="verProductor/<?= htmlspecialchars($producer->id_productora) ?>">
                                <?= htmlspecialchars($producer->nombre_productora) ?>
                            </a>
                        </h3>
                        <p class="card-text"><?= htmlspecialchars($producer->pais_origen) ?></p>
                        <div class="d-flex justify-content-between">
                            <!-- Botones de acción -->
                            <a href="eliminar/<?= htmlspecialchars($producer->id_productora) ?>" class="btn btn-danger btn-sm">Borrar</a>
                            <a href="editar/<?= htmlspecialchars($producer->id_productora) ?>" class="btn btn-primary btn-sm">Actualizar</a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>    
</div>

<?php require 'Templates/Layout/footer.phtml' ?>

           
   