<?php require 'Templates/Layout/header.phtml' ?>

<ul class="container">
    <div class="row">
        <?php foreach($producer as $producer): ?>
            <li class="col">
                <div class="producer-card">
                    <!-- Nombre de la película y el género -->
                    <div class="film-info">
                        <h3><?= htmlspecialchars($producer->nombre_productora) ?></h3>
                        <p><?= htmlspecialchars($producer->año_fundacion) ?></p>
                    </div>
                    <a href="eliminar/<?= $producer->id_productoras ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
                    <a href="editar/<?= $producer->id_productoras ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Actualizar</a>
                </div>
            </li>
        <?php endforeach ?>
    </div>    
</ul>

<?php require 'Templates/Layout/footer.phtml' ?>

           
   