
<body>
<?php require 'Templates/Layout/header.phtml' ?>
<?php if (isset($producer)): ?>
    <div class="container mt-5">
        <!-- Información de la productora -->
        <div class="row mt-4">
            <div class="col-md-4">
            <!--logo-->
            </div>
            <div class="col-md-8">
                <h1 class="text-center"><?= htmlspecialchars($producer->nombre_productora) ?></h1>
                <p><strong>País:</strong> <?= htmlspecialchars($producer->pais_origen) ?></p>
                <p><strong>Año de fundación:</strong> <?= htmlspecialchars($producer->año_fundacion) ?></p>
                <p><strong>Fundadores:</strong> <?= htmlspecialchars($producer->fundador_es) ?></p>
            </div>
        </div>

        <!-- Botón para volver -->
        <div class="row mt-5">
            <div class="col-md-12 text-center">
                <a href="producers" class="btn btn-primary">Volver</a>
            </div>
        </div>
    </div>
<?php else: ?>
    <p>Productora no encontrada.</p>
<?php endif; ?>

</body>
