<footer class="footer text-light py-3 mt-5">
    <div class="container text-center">
        <p>Grupo 140 - Plataforma de Películas</p>
        <p>Federico Poupeau Crego, Gmail: <a href="mailto:Poupeau04@gmail.com" class="text-light">Poupeau04@gmail.com</a></p>
        <p>Agostina Laffitte, Gmail: <a href="mailto:agoslaffitte17@gmail.com" class="text-light">agoslaffitte17@gmail.com</a></p>
    </div>
</footer>
</body>
</html>