<!DOCTYPE html>
<!-- 
    ESCRIBI EL NOMBRE DEL ARCHIVO COMO HEADE EN VEZ DE HEADER PORQUE
    SINO NO ME APARECIA NOSE EL POR QUE, MAÑANA EN LA CLASE DE CONSULTA
    PREGUNTO.
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <title>Netflix</title>
</head>
<body>
<header>
       <h1>hola</h1>
    </header>
</body>
</html>

