<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <link rel="icon" href="img/Logo-Ventana.png" type="image/x-icon">
    <title>Netflix</title>
</head>
<body class="bg-dark text-white">

    <header class="header">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <a class="navbar-brand" href="<?= BASE_URL ?>inicio">
                    <img src="img/Logo-Ventana.png" alt="logo" width="100">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a href="<?= BASE_URL ?>inicio" class="nav-link">Inicio</a>
                        </li>
                        <?php if ($this->user): ?>
                            <li class="nav-item">
                                <a href="<?= BASE_URL ?>agregar" class="nav-link">Agregar película</a>
                            </li>
                            <li class="nav-item">
                                <a href="<?= BASE_URL ?>agregarProductora" class="nav-link">Agregar productoras</a>
                            </li>
                        <?php endif; ?>
                        <li class="nav-item">
                            <a href="<?= BASE_URL ?>productora" class="nav-link">Productoras</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <?php if($this->user): ?>
                            <span class="navbar-text me-3"><?= $this->user->email ?></span>
                            <a href="<?= BASE_URL ?>logout" class="btn btn-outline-danger">Salir</a>
                        <?php else: ?>
                            <a href="<?= BASE_URL ?>showLogin" class="btn btn-outline-primary me-2">Login</a>
                            <a href="<?= BASE_URL ?>signup" class="btn btn-outline-secondary me-2">Sign up</a>
                        <?php endif; ?>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="b-example-divider"></div>
