
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <title>Netflix</title>
</head>
<body class="prueba">

    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <div class="col-md-3 mb-2 mb-md-0">
            <a href="" class="d-inline-flex link-body-emphasis text-decoration-none">
             <img src="img/netflix.webp" alt="logo">
            </a>
        </div>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="<?=BASE_URL ?>inicio" class="nav-link px-2 link-secondary">Inicio</a></li>
            
            <!-- muestro solo si esta logueado -->
            <?php if ($this->user): ?>
                    <li><a href="<?= BASE_URL ?>agregar" class="nav-link px-2">Agregar película</a></li>
                    <li><a href="<?= BASE_URL ?>agregarProductora" class="nav-link px-2">Agregar productoras</a></li>
            <?php endif; ?>

            <li><a href="<?= BASE_URL ?>productora" class="nav-link px-2">Productoras</a></li>
        </ul>
        <!-- AQUI SE MUESTRA EL USUARIO LOGUEADO -->
                <?php if($this->user): ?>
                    <span class="navbar-text me-3"><?= $this->user->email ?></span>
                <?php endif; ?>
                <?php if($this->user): ?>
                    <a href="<?= BASE_URL ?>logout" class="btn btn-outline-danger">Salir</a>
                <?php endif; ?>

                <?php if (!$this->user): ?>
    <!-- Mostrar botones de Login y Sign up solo si el usuario NO está logueado -->
    <a href="<?= BASE_URL ?>showLogin" class="btn btn-outline-primary me-2">Login</a>
    <a href="<?= BASE_URL ?>signup" class="btn btn-outline-secondary me-2">Sign up</a>
<?php endif; ?>

        </header>
    </div>

    <div class="b-example-divider"></div>



