
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../../css/style.css">
    <title>Netflix</title>
</head>
<body>

    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <div class="col-md-3 mb-2 mb-md-0">
            <a href="" class="d-inline-flex link-body-emphasis text-decoration-none">
                <img src="img/netflix.webp" alt="Logo"/>
            </a>
        </div>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">

            <li><a href="inicio" class="nav-link px-2 link-secondary">inicio</a></li>
            <li><a href="agregar" class="nav-link px-2">agregar</a></li>
            <li><a href="productor" class="nav-link px-2">Productor</a></li>
        </ul>
            <?php if($this->user): ?>
                <span class="navbar-text"><?= $this->user->email ?></span>
            <?php endif; ?>

            <div class="col-md-3 text-end">
                <a href="<?= BASE_URL ?>showLogin" class="btn btn-outline-primary me-2">Login</a>
                <button type="button" class="btn btn-primary">Sign-up</button>
            </div>
        </header>
    </div>

    <div class="b-example-divider"></div>
</body>
</html>

